openapi: 3.0.3
info:
  version: 0.1.0
  title: User Encouragement API
  description: API for User Encouragement service
servers:
  - url: http://user-encouragement-service:{port}/api/rest/v1
paths:
  /api/rest/v1/version:
    get:
      description: Returns a version of this service.
      tags:
       - Version
      operationId: version
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceVersionResponse'
        '400':
          description: Bad request
        '500':
          description: Server internal error
  /api/rest/v1/encouragement-program:
    post:
      description: Creates new Encouragement Program.
      operationId: createEncouragementProgram
      tags:
        - Encouragement Program
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEncouragementProgramRequest'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '500':
          description: Server internal error
  /api/rest/v1/points/calculate:
    post:
      description: Calculates points based on transaction total.
      tags:
        - Points
      operationId: calculatePoints
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PointsCalculationRequest'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '500':
          description: Server internal error
components:
  schemas:
    ServiceVersion:
      type: object
      properties:
        version:
          type: string
          minLength: 1
      required:
        - version
    EncouragementProgram:
      type: object
      properties:
        name:
          type: string
          minLength: 2
        pointFactor:
          type: number
          format: float
        pointsCalculationThreshold:
          type: integer
          format: int32
    TransactionInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        encouragementAccountId:
          type: integer
          format: int64
        total:
          type: number
          format: double
      required:
        - id
        - customerId
        - encouragementAccountId
        - total
    Response:
      type: object
      properties:
        resource:
          type: string
          minLength: 1
        timestamp:
          type: string
          format: date-time
        data:
          type: object
      required:
        - resource
        - timestamp
    ServiceVersionResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/ServiceVersion'
    CreateEncouragementProgramRequest:
      type: object
      properties:
        encouragementProgram:
          $ref: '#/components/schemas/EncouragementProgram'
    PointsCalculationRequest:
      type: object
      properties:
        transaction:
          $ref: '#/components/schemas/TransactionInfo'

